version: "2"

services:
  data:
    build: docker/data/.
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qo5ee
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    volumes_from:
      - data
  api:
    image: richarvey/nginx-php-fpm
    container_name: api
    ports:
      - "8081:80"
    volumes:
      - ./docker/pizzahut_services:/usr/share/nginx/html
    links:
      - mysql
  cassandra:  
    image: cassandra:2.2.4
    container_name: cassandra
    ports:
      - "9042:9042" 
  web:
    image: mashape/kong
    depends_on:
      - "cassandra"
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - cassandra
  ui:
    image: pgbi/kong-dashboard
    ports:
      - "8080:8080"
