#data:
#  build: docker/mysql-data/.
#mysql:
#  image: mysql:5.5
#  container_name: mysql
#  ports:
#    - "3306:3306"
#  environment:
#    MYSQL_DATABASE: qo5ee
#    MYSQL_USER: qo5cms
#    MYSQL_PASSWORD: qo5cms
#    MYSQL_ROOT_PASSWORD: qo5cms
#  volumes:
#    - ./docker/mysql-data:/docker-entrypoint-initdb.d
#  volumes_from:
#    - data
#api:
#  image: richarvey/nginx-php-fpm
#  container_name: api
#  ports:
#    - "8081:80"
#  volumes:
#    - ./docker/api_services:/usr/share/nginx/html
#  environment:
#    ENVIRONMENT: development
#  links:
#    - mysql
cassandra-data:
  container_name: cassandra-data
  build: docker/cassandra-data/.
cassandra:
  image: cassandra:2.2.5
  container_name: kong-database
  ports:
    - "9042:9042" 
  volumes_from:
    - cassandra-data
kong:
  build: docker/kong/.
  container_name: kong
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"
  environment:
   CASSANDRA_HOSTNAME: kong-database
   CASSANDRA_PORT: 9042
  security_opt:
    - seccomp:unconfined
  links:
    - cassandra
ui:
  image: pgbi/kong-dashboard
  ports:
    - "8080:8080"
